CREATE TABLE IF NOT EXISTS users (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(255)    NOT NULL,
    enabled     BOOLEAN         NOT NULL,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_cart_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS items (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)    NOT NULL,
    description VARCHAR(1024)   NOT NULL,
    img_path    VARCHAR(255)    NOT NULL,
    price       BIGINT          NOT NULL
);

CREATE TABLE IF NOT EXISTS cart_items (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT          NOT NULL,
    item_id     BIGINT          NOT NULL,
    quantity    INT             NOT NULL,

    CONSTRAINT uk_cart_items_user_id_item_id UNIQUE (user_id, item_id),
    CONSTRAINT fk_cart_items_user_id FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_cart_items_item_id FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT chk_cart_item_quantity CHECK (quantity >= 0)
);

CREATE TABLE IF NOT EXISTS orders (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT          NOT NULL,
    created_at  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status      VARCHAR(50)     NOT NULL DEFAULT 'CREATED',

    CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS order_items (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT          NOT NULL,
    title       VARCHAR(255)    NOT NULL,
    price       BIGINT          NOT NULL,
    quantity    INT             NOT NULL,

    CONSTRAINT fk_order_items_order_id FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT chk_order_item_price CHECK (price >= 0),
    CONSTRAINT chk_order_item_quantity CHECK (quantity > 0)
);

