spring.application.name=payment-service

payment.initial-balance=1000000

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/my-market
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/my-market/protocol/openid-connect/certs

server.port=8081